"""DeepSeek constants and shared literal type aliases."""

from __future__ import annotations

import re
from typing import Literal

DEEPSEEK_STABLE_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_BETA_BASE_URL = "https://api.deepseek.com/beta"
DEEPSEEK_REASONER_MODEL = "deepseek-reasoner"
DEEPSEEK_CHAT_MODEL = "deepseek-chat"
DEEPSEEK_MODEL = DEEPSEEK_REASONER_MODEL
MAX_RETRIES_DEFAULT = 2
DEEPSEEK_REASONER_MAX_COMPLETION_TOKENS = 64000
DEEPSEEK_CHAT_MAX_COMPLETION_TOKENS = 8192
DEFAULT_MAX_COMPLETION_TOKENS = DEEPSEEK_REASONER_MAX_COMPLETION_TOKENS
DEFAULT_TIMEOUT_SECONDS = 120.0
DEFAULT_HTTP_RETRIES = 1
DEFAULT_TEMPERATURE = 0.2
SUMMARY_LINE_COUNT_MIN = 8
SUMMARY_LINE_COUNT_MAX = 60
SUMMARY_LINE_WORD_TARGET = 14
SUMMARY_LINE_WORD_FLOOR = 7.0
SUMMARY_MAX_SHORT_QUESTION_RATIO = 0.35
ERROR_DIGEST_MAX_CHARS = 280
TOOL_EVENT_DETAILS_MAX_CHARS = 1200
TOKEN_BUDGET_WORD_FACTOR = 1.8
TOKEN_BUDGET_SAFETY_BUFFER = 256
TOKEN_BUDGET_MIN = 512
DEEPSEEK_STREAM_EVENT_PREFIX = "[DEEPSEEK_STREAM] "
DEFAULT_AGENT_MAX_TOOL_ROUNDS = 10
DEFAULT_AGENT_READ_MAX_LINES = 120
DEFAULT_AGENT_WRITE_MAX_CHARS = 12000
DEFAULT_AGENT_WRITE_MAX_FILE_CHARS = 400000
DEFAULT_AGENT_LOOP_EXHAUSTION_POLICY = "auto_salvage"
DEFAULT_AGENT_MAX_REPEATED_WRITE_OVERWRITES = 2
DEFAULT_AGENT_PERSIST_REASONING_CONTENT = False
DEFAULT_AGENT_ALLOW_MODEL_FALLBACK = False
EVALUATE_SCRIPT_TOOL_NAME = "evaluate_script_constraints"
READ_TRANSCRIPT_LINES_TOOL_NAME = "read_transcript_lines"
COUNT_WORDS_TOOL_NAME = "count_words"
WRITE_OUTPUT_SEGMENT_TOOL_NAME = "write_output_segment"
STAGED_OUTPUT_READY_MARKER = "STAGED_OUTPUT_READY"
DEFAULT_BUDGET_FAILURE_POLICY = "degraded_success"
DEFAULT_AGENT_TOOL_MODE = "full_agentic"
CONTEXT_WINDOW_ROLLOVER_LEFT_RATIO = 0.30
CONTEXT_USAGE_UPDATE_INTERVAL_SECONDS = 1.0
CONTEXT_SUMMARY_MAX_TOKENS = 1024
CONTEXT_SUMMARY_MAX_CHARS = 12000
DEEPSEEK_CHAT_LOG_ROOT_DIR = "deepseek_chat_logs"
DEEPSEEK_CHAT_LOG_FILE = "trace.ndjson"
DEEPSEEK_CHAT_LOG_META_FILE = "run_meta.json"
DEEPSEEK_CHAT_LOG_TIMESTAMP_FORMAT = "%Y%m%dT%H%M%SZ"
DEEPSEEK_CHAT_LOG_STREAM_FLUSH_INTERVAL_SECONDS = 10.0
DISFLUENCY_PATTERN = re.compile(r"\b(?:um+|uh+|ah+)\b", re.IGNORECASE)
ErrorType = Literal[
    "api_error",
    "malformed_json",
    "truncated_json",
    "truncated_output",
    "schema_validation",
    "empty_response",
    "tool_loop_exhausted",
]
EndpointMode = Literal["beta", "stable"]
BudgetFailurePolicy = Literal["degraded_success", "strict_fail"]
AgentToolMode = Literal["off", "constraints_only", "full_agentic"]
AgentLoopExhaustionPolicy = Literal["auto_salvage", "fail_fast"]
